# references:
# # * http://www.objc.io/issue-6/travis-ci.html
# # * https://github.com/supermarin/xcpretty#usage
#
language: objective-c
osx_image: xcode9
cache: cocoapods
env:
- SWIFT_VERSION=4.2
podfile: Podfile
before_install:
#- gem install cocoapods # Since Travis is not always on latest version
#- pod repo update
#- pod install --project-directory=Example
- gem install bundler
- bundle install
- pod repo update
- pod deintegrate
- pod install
script:
- set -o pipefail && xcodebuild test -workspace Kumi.xcworkspace -scheme KumiTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' | xcpretty
# - pod lib lint
